/**
 * System status — what is live, what is simulated, what is degraded.
 * Surfaced in the interface so nobody has to guess which mode they are in.
 */

import { reasoningConfigured, MODEL } from '@/lib/agent/llm';
import { pipelineShape } from '@/lib/aegis/pipeline';
import { ragShape } from '@/lib/aegis/rag';
import { DOCUMENTS } from '@/lib/aegis/corpus';
import { INCIDENT } from '@/lib/aegis/incident';

export const dynamic = 'force-dynamic';

export async function GET() {
  const live = reasoningConfigured();
  return Response.json({
    incident: INCIDENT,
    reasoning: {
      configured: live,
      model: live ? MODEL : null,
      mode: live ? 'live' : 'fallback',
      note: live
        ? 'Reasoning layer available. Recommendations are produced by the model and marked as such.'
        : 'No reasoning credentials on this deployment. Deterministic rule engines produce every recommendation, and each is labelled RULE ENGINE.',
    },
    subsystems: [
      { id: 'vision', label: 'Vision analysis', status: 'simulated', note: 'Flood and damage fields generated by the incident model. Swap for U-Net / YOLO inference in deployment.' },
      { id: 'zones', label: 'Zone prioritisation', status: 'working', note: 'Transparent weighted severity over the 100-zone grid.' },
      { id: 'drones', label: 'Drone intelligence', status: 'simulated', note: 'Full flight, battery, wind and detection model. No hardware.' },
      { id: 'decision', label: 'Resource decision', status: live ? 'working' : 'fallback', note: live ? 'Agentic reasoning with read-only investigation tools.' : 'Deterministic rule engine.' },
      { id: 'routing', label: 'Safe routing', status: 'working', note: 'Dijkstra over the zone graph with hard edge removal.' },
      { id: 'dispatch', label: 'Dispatch', status: 'simulated', note: 'Orders are generated and rendered. No SMS or WhatsApp is transmitted.' },
      { id: 'assistant', label: 'Preparedness assistant', status: 'working', note: `Self-correcting RAG over ${DOCUMENTS.length} doctrine documents. Retrieval runs offline.` },
      { id: 'register', label: 'Audit register', status: 'working', note: 'Append-only. Process-local in this prototype.' },
    ],
    graphs: { pipeline: await pipelineShape(), rag: await ragShape() },
  });
}
